name: safeguardher_women_safety_app
description: "Women Safety App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  noise_meter: ^5.0.2
  geolocator: ^11.0.0
  speech_to_text: ^7.3.0
  permission_handler: ^11.3.0
  url_launcher: ^6.2.5
  fluttertoast: ^8.2.4
  flutter_contacts: ^1.1.7
  record: ^6.1.2
  path_provider: ^2.1.2
  google_maps_flutter: ^2.13.1

  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12

  google_sign_in: ^6.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/